Documented Keep Alive settings for gRPC and database node.
kurrent-io/documentation pull request #276
Opened 2021-02-23 15:56 UTC by oskardudycz

1. Added KeepAlive settings in gRPC client configuration wizard:
![obraz](https://user-images.githubusercontent.com/5562528/108869981-01f36680-75f8-11eb-9f83-d6fc22231b01.png)

2. Added information with the description in the database node configuration.

2021-02-23 16:10 UTC, alexeyzimarev requested changes

2021-02-23 16:10 UTC, alexeyzimarev commented on docs/server/v20/server/networking/http.md
> +
Maybe remove this line?

2021-02-23 16:20 UTC, oskardudycz commented on docs/server/v20/server/networking/http.md
> +
Removed 👍

2021-02-24 09:35 UTC, mat-mcloughlin approved these changes
Looks good from the UI perspective

2021-02-24 10:04 UTC, alexeyzimarev approved these changes

2021-02-24 10:33 UTC, merged