Configured import of 21.2 docs from the main database repository.
kurrent-io/documentation pull request #286
Opened 2021-03-02 12:22 UTC by oskardudycz

Configured import of 21.2 docs from the main database repository.

Updated import-client-docs.js script to support docs import again.

2021-03-03 08:37 UTC, ylorph approved these changes

2021-03-03 08:39 UTC, ylorph requested changes
https://deploy-preview-286--developers-eventstore.netlify.app/server/generated/21.2/docs/introduction/
'Welcome to 20.10' instead of 21.2

2021-03-03 08:58 UTC, oskardudycz commented
@ylorph thanks for the great catch!

However, changes to fix are required in the other PR. I applied it there:
- PR: https://github.com/EventStore/EventStore/pull/2831 
- commit with a fix: https://github.com/EventStore/EventStore/pull/2831/commits/29276e771fdcb77489ba1ff712eeab50f73b8479

2021-03-03 09:02 UTC, mat-mcloughlin approved these changes

2021-03-08 12:59 UTC, ylorph approved these changes

2021-03-08 14:40 UTC, merged