Added Go gRPC snippets
kurrent-io/documentation pull request #450
Opened 2021-09-28 13:06 UTC by oskardudycz

2021-10-12 08:59 UTC, mat-mcloughlin approved these changes

2021-10-12 08:59 UTC, mat-mcloughlin commented
Looks good but I can't speak to the correctness of the go samples

2021-10-12 13:13 UTC, ylorph requested changes

2021-10-12 13:13 UTC, ylorph commented on docs/clients/grpc/README.md
> +::: code-group-item Go
this section should go above c# & Java (up a fex line )

2021-10-12 13:13 UTC, ylorph commented on docs/clients/grpc/projections.md
> +<xode-block title="Go" code="connectionString">
needs a line feed to render correctly
this while block needs to be befor the java one

2021-10-12 13:13 UTC, ylorph commented on docs/clients/grpc/projections.md
>  </xode-block>
needs a line feed just before this line to render correctly

2021-10-12 13:13 UTC, ylorph commented on docs/clients/grpc/projections.md
> +// This is currently not available in the Go client
```suggestion
```
// This is currently not available in the Go client
```
```

2021-10-12 13:13 UTC, ylorph commented on docs/clients/grpc/projections.md
> +// This is currently not available in the Go client
```suggestion
```
// This is currently not available in the Go client
```
```

2021-10-12 13:13 UTC, ylorph commented on docs/clients/grpc/projections.md
> +// This is currently not available in the Go client
```suggestion
```
// This is currently not available in the Go client
```
```

2021-10-12 13:13 UTC, ylorph commented on docs/clients/grpc/projections.md
> +// This is currently not available in the Go client
```suggestion
```
// This is currently not available in the Go client
```
```

2021-10-12 13:13 UTC, ylorph commented on docs/clients/grpc/projections.md
> +// This is currently not available in the Go client
```suggestion
```
// This is currently not available in the Go client
```
```

2021-10-12 13:13 UTC, ylorph commented on docs/clients/grpc/projections.md
> +// This is currently not available in the Go client
```suggestion
```
// This is currently not available in the Go client
```
```

2021-10-12 13:13 UTC, ylorph commented on docs/clients/grpc/projections.md
> +// This is currently not available in the Go client
```suggestion
```
// This is currently not available in the Go client
```
```

2021-10-12 13:13 UTC, ylorph commented on docs/clients/grpc/projections.md
> +// This is currently not available in the Go client
```suggestion
```
// This is currently not available in the Go client
```
```

2021-10-12 13:13 UTC, ylorph commented on docs/clients/grpc/projections.md
> +// This is currently not available in the Go client
```suggestion
```
// This is currently not available in the Go client
```
```

2021-10-12 13:13 UTC, ylorph commented on docs/clients/grpc/projections.md
> +// This is currently not available in the Go client
```suggestion
```
// This is currently not available in the Go client
```
```

2021-10-12 15:04 UTC, oskardudycz commented
@ylorph, thank you for the review and finding those issues. I fixed all of them in https://github.com/EventStore/documentation/pull/450/commits/919328fb249ea14ca2a2da0561e11fe403186dad.

2021-10-13 08:03 UTC, ylorph commented on docs/clients/grpc/reading-events.md
> +:::
do we have a sample for go line 180 ?

2021-10-13 08:39 UTC, oskardudycz commented on docs/clients/grpc/reading-events.md
> +:::
@ylorph, thanks for catching that. It is fixed in https://github.com/EventStore/documentation/pull/450/commits/15c40d572c6193473b281db6cd8c4d0b64a43c44.

2021-10-13 09:57 UTC, ylorph approved these changes

2021-10-14 06:49 UTC, merged