Adding documentation for resizing cluster nodes and ESDB version
kurrent-io/documentation pull request #451
Opened 2021-10-04 11:07 UTC by mat-mcloughlin

2021-10-04 11:11 UTC, oskardudycz approved these changes

2021-10-04 12:29 UTC, ylorph approved these changes

2021-10-04 12:36 UTC, alexeyzimarev requested changes

2021-10-04 12:36 UTC, alexeyzimarev commented on docs/cloud/ops/README.md
> +The ability to do an online resizing of cluster nodes is part of our future roadmap. Until that point, if you need to resize the nodes you should perform a [backup](#manual-backup) and [restore](#res
```suggestion
The ability to do an online resizing of cluster nodes is part of our future roadmap. Until that point, if you need to resize the nodes, you should perform a [backup](#manual-backup) and [restore](#restore-from-backup) to a new cluster. You can choose a larger or smaller node size, as well as a different cluster topology. You can then switch your applications over to the connection string for the new cluster.
```

2021-10-04 12:36 UTC, alexeyzimarev commented on docs/cloud/ops/README.md
> +This is on offline process and any new events appended to the database between the backup and restore will be lost. If you want to perform an online resize then the [replicator](replicator.eventstore
```suggestion
Using backup-restore for changing the cluster size should typically be done when all the write loads are turned off. Any new events appended to the database between the backup and restore will be lost. If you want to perform an online resize, then the [replicator](https://replicator.eventstore.org) can be used to keep two databases in sync.  Please ensure you understand the [limitations](https://replicator.eventstore.org/docs/limitations/) of the replication tool.
```

2021-10-04 12:36 UTC, alexeyzimarev commented on docs/cloud/ops/README.md
> +This is on offline process and any new events appended to the database between the backup and restore will be lost. If you want to perform an online upgrade then the [replicator](replicator.eventstor
```suggestion
Using backup-restore for changing the EventStoreDB version should typically be done when all the write loads are turned off. Any new events appended to the database between the backup and restore will be lost. If you want to perform an online resize, then the [replicator](https://replicator.eventstore.org) can be used to keep two databases in sync.  Please ensure you understand the [limitations](https://replicator.eventstore.org/docs/limitations/) of the replication tool.
```

2021-10-04 12:36 UTC, alexeyzimarev commented on docs/cloud/ops/README.md
> +The ability to do an online upgrade of the version of EventStoreDB your cluster is running is part of our future roadmap. Until that point, if you need to upgrade server versions you should perform a
```suggestion
The ability to do an online upgrade of EventStoreDB version of your cluster is part of our future roadmap. Until that point, if you need to upgrade server versions, you should perform a [backup](#manual-backup), and [restore](#restore-from-backup) to a new cluster. When restoring the backup, you can choose EventStoreDB version you need. You can then switch your applications over to the new connection string.
```

2021-10-05 08:08 UTC, alexeyzimarev approved these changes

2021-10-05 13:34 UTC, merged