Adds documentation for new AWS CloudWatch sinks
kurrent-io/documentation pull request #537
Opened 2022-06-30 22:57 UTC by TimSimpson

2022-07-01 10:28 UTC, ylorph requested changes

2022-07-01 10:28 UTC, ylorph commented on docs/cloud/integrations/README.md
> +Event Store Cloud offers integrations between internal sources such as cluster health, [issue](#issues) detection, [notifications](#notifications) events, EventStore DB [logs], EventStore DB [metrics
```suggestion
Event Store Cloud offers integrations between internal sources such as cluster health, [issue](#issues) detection, [notifications](#notifications) events, EventStore DB [logs](#logs), EventStore DB [metrics](#metrics) and sinks which include external services such as Slack and Amazon CloudWatch.
```

2022-07-01 10:28 UTC, ylorph commented on docs/cloud/integrations/README.md
> +* [Metrics](#metrics) - these are the metrics generated by both the EventStore Cloud issue detection processes running on the each cluster node and EventStore DB itself.
```suggestion
* [Metrics](#metrics) - these are the metrics generated by both EventStore Cloud issue detection processes running on each cluster node and EventStore DB itself.
```

2022-07-01 10:28 UTC, ylorph commented on docs/cloud/integrations/README.md
> +**NOTE: Logs are currently in beta and may change over time. The data coming from this source may change over time.**
```suggestion
::: note
Logs are currently in beta and may change over time. The data coming from this source may change over time.**
:::
```

2022-07-01 10:28 UTC, ylorph commented on docs/cloud/integrations/README.md
> +**NOTE: Logs are currently in beta and may change over time. The data coming from this source may change over time.**
```suggestion
::: note
Logs are currently in beta and may change over time. The data coming from this source may change over time.**
:::
```

2022-07-01 10:28 UTC, ylorph commented on docs/cloud/integrations/README.md
> +Metrics are name / value pairs which are generated by EventStore DB itself as well as detection processes running on the host.
```suggestion
Metrics are name / value pairs generated by EventStore DB itself as well as detection processes running on the host.
```

2022-07-01 10:28 UTC, ylorph commented on docs/cloud/integrations/README.md
> +* [AwsCloudWatchLogs](#aws-cloudwatch-logs-sink) - **BETA** AWS CloudWatch allows you to track metrics, display them with create custom dashboards, create alarms from them, etc.
```suggestion
* [AwsCloudWatchLogs](#aws-cloudwatch-logs-sink) - **BETA** Amazon CloudWatch allows you to track metrics, display them with custom dashboards, create alarms from them.
```

2022-07-01 10:28 UTC, ylorph commented on docs/cloud/integrations/README.md
> +* [AwsCloudWatchMetrics](#aws-cloudwatch-metrics-sink) - **BETA** AWS CloudWatch allows for logs to be uploaded, viewed and searched, and consumed by other AWS services.
```suggestion
* [AwsCloudWatchMetrics](#aws-cloudwatch-metrics-sink) - **BETA** Amazon CloudWatch allows for logs to be uploaded, viewed and searched, and consumed by other AWS services.
```

2022-07-01 10:28 UTC, ylorph commented on docs/cloud/integrations/README.md
> +**NOTE: The AwsCloudWatchLogs sink is currently in closed beta and may change over time. To access it, please contact support.**
```suggestion
::: note
The AwsCloudWatchLogs sink is currently in closed beta and may change over time. To access it, please contact support.
:::
```

2022-07-01 10:28 UTC, ylorph commented on docs/cloud/integrations/README.md
> +AWS CloudWatch is a monitoring service. The "logs" portion of its functionality is separated into it's own integration in the EventStore Cloud for ease of use.
```suggestion
AWS CloudWatch is a monitoring service. The "logs" portion of its functionality is separated into it's own integration in EventStore Cloud for ease of use.
```

2022-07-01 10:28 UTC, ylorph commented on docs/cloud/integrations/README.md
> +*NOTE: If you're using Terraform, instructions on how to perform the steps below can be found [here](https://github.com/EventStore/terraform-provider-eventstorecloud/blob/trunk/docs/resources/integra
```suggestion
:::note 
If you're using Terraform, instructions on how to perform the steps below can be found [here](https://github.com/EventStore/terraform-provider-eventstorecloud/blob/trunk/docs/resources/integration_awscloudwatch_logs.md#example-usage).
:::
```

2022-07-01 10:28 UTC, ylorph commented on docs/cloud/integrations/README.md
> +**NOTE: You should create credentials especially for use with the EventStore Cloud integration which only have access to the CloudWatch Log group, as shown here.**
```suggestion
::: note 
You should create dedicated credentials for use with the EventStore Cloud integration that only have access to the CloudWatch Log group, as shown here.
:::
```

2022-07-01 10:28 UTC, ylorph commented on docs/cloud/integrations/README.md
> +**NOTE: The AwsCloudWatchMetrics sink is currently in closed beta and may change over time. To access it, please contact support.**
```suggestion
::: note
The AwsCloudWatchMetrics sink is currently in closed beta and may change over time. To access it, please contact support.
:::
```

2022-07-01 10:28 UTC, ylorph commented on docs/cloud/integrations/README.md
> +AWS CloudWatch is a monitoring service. The "metrics" portion of its functionality is separated into its own integration in the EventStore Cloud for ease of use.
```suggestion
AWS CloudWatch is a monitoring service. The "metrics" portion of its functionality is separated into its own integration in EventStore Cloud for ease of use.
```

2022-07-01 10:28 UTC, ylorph commented on docs/cloud/integrations/README.md
> +*NOTE: If you're using Terraform, instructions on how to perform the steps below can be found [here](https://github.com/EventStore/terraform-provider-eventstorecloud/blob/trunk/docs/resources/integra
```suggestion
:::note 
If you're using Terraform, instructions on how to perform the steps below can be found [here](https://github.com/EventStore/terraform-provider-eventstorecloud/blob/trunk/docs/resources/integration_awscloudwatch_metrics.md#example-usage).
:::
```

2022-07-01 10:28 UTC, ylorph commented on docs/cloud/integrations/README.md
> +**NOTE: You should create credentials especially for use with the EventStore Cloud integration which only have permission to perform the `cloudwatch:PutMetricData` action on a small set of namespaces
```suggestion
::: note
You should create credentials especially for use with the EventStore Cloud integration which only have permission to perform the `cloudwatch:PutMetricData` action on a small set of namespaces, as shown here.
:::
```

2022-07-01 14:02 UTC, ylorph requested changes

2022-07-01 14:02 UTC, ylorph commented on docs/cloud/integrations/README.md
> +The EventStore Cloud backend may take up to 10 minutes to install new log integrations.
```suggestion
Log Integration with EventStore Cloud will take a few minutes to be fully active
```
Trying not to give expectations there .

2022-07-01 14:02 UTC, ylorph commented on docs/cloud/integrations/README.md
> +The EventStore Cloud backend may take up to 10 minutes to install new metrics integrations.
```suggestion
Metrics integration with EventStore Cloud will take a few minutes to be fully activated
```
Trying to not give expectations on timing

2022-07-04 10:09 UTC, alexeyzimarev approved these changes

2022-07-04 10:09 UTC, ylorph approved these changes

2022-07-04 10:09 UTC, merged