DOC-40 more redirects
kurrent-io/documentation pull request #596
Opened 2023-10-06 15:57 UTC by rmalik-es

2023-10-06 17:25 UTC, rsowald approved these changes

2023-10-06 17:27 UTC, rsowald requested changes
we need to remove line 57 because we do not want to redirect from 20.10. That version 20.10 is still supported

2023-10-09 16:53 UTC, rmalik-es commented
Removed. The 20.10 broken links may need manual redirects, but those will be dealt with in a separate PR.

2023-10-10 12:20 UTC, cdevarenne approved these changes

2023-10-10 18:57 UTC, rsowald approved these changes

2023-10-11 08:49 UTC, merged