Add docs for cloud Multi-factor authentication (MFA)
kurrent-io/documentation pull request #630
Opened 2023-12-15 12:01 UTC by arwinneil

2023-12-28 17:32 UTC, rmalik-es reviewed
**Suggested changes**

Consider changing "ensure your device is ready" to "ensure your device is prepared"

And edit "Follow the guided prompts to complete the MFA enrollment process" to "Follow the guided prommpts to complete the enrollment".

And edit "You will be prompted for your password as well as an authenticator code as part of the process" to "You will be prompted for your password and an authenticator code as part of this process".

And finally, "Alternatively, if you choose to get a token through the  Cloud Console..." to "Alternatively, if you prefer to obtain a token through the Cloud Console..."

Thanks

2024-01-04 08:05 UTC, arwinneil commented
Hello @rmalik-es
Applied the suggested changes, thank you!

2024-01-04 17:27 UTC, rsowald commented on docs/cloud/intro/README.md
> +To enable Multi-factor Authentication (MFA) within the user interface, navigate to the `Preferences` section and click on the `Enable MFA`` button.
```suggestion
To enable Multi-factor Authentication (MFA) within the user interface, navigate to the `Preferences` section and click on the `Enable MFA` button. 
```

2024-01-04 17:27 UTC, rsowald commented on docs/cloud/intro/README.md
> +You will be prompted for you password and an authenticator code as part of the process.
```suggestion
You will be prompted for your password and an authenticator code as part of the process.
```

2024-01-09 18:35 UTC, cdevarenne commented on docs/cloud/intro/README.md
> +Our MFA solution currently integrates exclusively with authenticator apps, offering a convenient and secure method for users to verify their identities.  When setting up MFA, ensure your device is pr
```suggestion
Our MFA solution currently integrates exclusively with authenticator apps, offering a convenient and secure method for users to verify their identities.  When setting up MFA, ensure your device is ready to use, as the process involves generating and entering authenticator codes.
```

2024-01-09 18:36 UTC, cdevarenne approved these changes

2024-01-09 18:51 UTC, rsowald approved these changes

2024-01-11 11:22 UTC, George-Payne commented on docs/cloud/intro/images/mfa-setup-process.png
I thought that QR code didn't look right :slightly_smiling_face: 
(missed opportunity for a rick-roll)

2024-01-11 12:21 UTC, alexeyzimarev requested changes

2024-01-11 12:21 UTC, alexeyzimarev commented on docs/cloud/intro/README.md
> +Once MFA is enabled, tokens generated with the CLI are invalidated. To regain access, generate new tokens using the following command :
CLI -> `esc` command-line tool

following command : -> remove space

2024-01-11 12:21 UTC, alexeyzimarev commented on docs/cloud/intro/README.md
> +$ esc access tokens create
Remove dollar prompt, otherwise copy-paste won't work

2024-01-11 12:21 UTC, alexeyzimarev commented on docs/cloud/intro/README.md
> +Alternatively, if you prefer to obtain a token through the  Cloud Console, navigate to the [Authentication Tokens](https://console.eventstore.cloud/authentication-tokens) page and click on the `Reque
through the  Cloud Console -> two spaces between "the" and "Cloud", please remove one

2024-01-12 22:04 UTC, cdevarenne approved these changes

2024-01-12 22:07 UTC, cdevarenne requested changes

2024-01-12 22:07 UTC, cdevarenne commented on docs/cloud/intro/README.md
> +Once MFA is enabled, tokens generated with the `esc` command-line tool are invalidated. To regain access, generate new tokens using the following command :
```suggestion
Once MFA is enabled, tokens generated with the `esc` command-line tool are invalidated. To regain access, generate new tokens using the following command:
```

2024-01-13 00:00 UTC, cdevarenne approved these changes

2024-01-22 12:56 UTC, alexeyzimarev approved these changes

2024-01-22 12:56 UTC, merged