Document client code for performing hard delete in EventStoreDB
kurrent-io/documentation pull request #693
Opened 2024-08-30 17:11 UTC by CindyLoMinChung

Description
This pull request adds documentation for performing soft deletes and hard deletes in EventStoreDB using client code. The new documentation provides clear examples and guidelines on how to implement delete functionality programmatically, highlighting when and why using code is preferable over other methods such as the HTTP API.

Changes include:

Detailed explanation of soft delete and hard delete in EventStoreDB.
Code examples for implementing hard delete in different programming languages.
Clarifications on the benefits of using client code for hard delete operations.
This documentation aims to assist developers in better understanding and implementing hard deletes within their EventStoreDB applications.

Additional Notes
Special thanks to Jusbeer for his assistance in preparing this documentation.

2024-08-31 00:20 UTC, YoEight requested changes
The documentation is correct and well written. I would also mention that when "hard deleting", you can't reuse the stream name ever again. I think it's important to mention it because we met people who thought that hard deletes worked the same way deleting a table would in SQL databases. In ESDB's case, that stream name is doomed forever and will raised an exception when trying to append in it again.

2024-09-04 16:35 UTC, coloradomorrissey approved these changes

2024-09-30 20:28 UTC, alexeyzimarev commented
Please change it from code-group to tabs like in other snippets

2024-10-07 21:48 UTC, coloradomorrissey approved these changes

2024-10-07 21:49 UTC, coloradomorrissey commented
@YoEight would you review/approve, please (assuming your request was captured)

2024-10-08 10:02 UTC, YoEight approved these changes

2024-10-08 15:12 UTC, merged